# Generated by Django 4.0.6 on 2022-11-22 12:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_message_massage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='MassageUser',
            new_name='MessageUser',
        ),
    ]
